### ISSUE TITLE
Неверная ссылка

### ISSUE THREAD

**Issue by tembun** [mobx-cookbook/mobx-cookbook.github.io#20]
На странице "Поддержка" неверно указана ссылка на следующую страницу.
https://mobx-cookbook.github.io/support

**Comment by kubk** [comment]
@spleekz Спасибо!

@zapolnoch Есть какие-то общие способы исправить эту проблему? Не в первый раз уже. В прошлый раз проблема была из-за вложенных разделов. А теперь из-за того что 1 раздел - 1 статья. Было бы удобно в как-то самому в конфигурации указывать какая статья будет следующая, чтобы избегать этого бага.
