### ISSUE TITLE
bug: в результрующем примере Mobx в 50 строчек не обновляется значение количества кликов после первого клика

### ISSUE THREAD

**Issue by akaguny** [mobx-cookbook/mobx-cookbook.github.io#29]
Шаги:
1. открыта страница [MobX в 50 строчек кода#Результат](https://mobx-cookbook.github.io/mobx-inside#%D1%80%D0%B5%D0%B7%D1%83%D0%BB%D1%8C%D1%82%D0%B0%D1%82)
2. окончена загрузка примера работы кода
3. левым кликом мыши нажата кнопка инкремента счётчика кликов в примере

ОР:
Текст кнопки изменился с Clicked times: 0 на Clicked times: 1
ФР:
Текст кнопки остался неизменным.
Комментарий
После повторного нажатия на кнопку текст кнопки станет Clicked times: 2

Демонстрация:
[screen-capture.webm](https://github.com/mobx-cookbook/mobx-cookbook.github.io/assets/3505959/054b7817-f426-4c35-8ef9-15b334004341)

**Comment by kubk** [comment]
Спасибо за обнаруженный баг. Странно, в моём старом примере этой проблемы нет: https://codesandbox.io/s/mystifying-jones-vc18p?file=/index.js:0-1199

Я его вставил в редактор prism и там проблема есть. Нужно поразбираться, так как это может быть связано с babel / prism / со строгим режимом React
