### ISSUE TITLE
Discussion: UX: я как пользователь не понимаю как начать пользоваться книгой на главной странице 

### ISSUE THREAD

**Issue by akaguny** [mobx-cookbook/mobx-cookbook.github.io#32]
Проблема: я как пользователь на главной странице не понимаю как начать пользоваться ресурсом
Разбор:
- Входная точка находится в контексте простыни текста
- Нет понятного действия для страницы
Комментарий
Этим страдают многие порталы на docusarius, но можно например сделать по аналогии с https://samarkand-guide.com/ .
Также docusarius, но есть верхнее меню, кнопка с главным действием - entry point перед глазами и в общем объём текста меньше.
Прошу отнестись к задаче творчески =)

**Comment by kubk** [comment]
Всё так, это проблема docusaurus что главная страница не часть книги, sidebar не отображается, только верхнее меню. 

Сайт про Самарканд сделан классно. Можем главную страницу сделать в похожем стиле. Мне только не очень нравится что есть 2 источника информации - сайдбар и верхнее меню. Поэтому на главной странице добавлю краткую информацию про книгу и хорошо заметную кнопку 👍

**Comment by kubk** [comment]
https://mobx-cookbook.github.io/

Задеплоено, спасибо что напомнил про эту проблему 👍

**Comment by akaguny** [comment]
Пожалуйста. С точки зрения интерактивной книги могу привести хороший пример (ИМХО конечно)
https://mfrachet.github.io/create-frontend-framework/
Это книга про то как шаг за шагом разработать прототип веб фреймворка, попутно даются сравнения и общая информация.
Советую всем эту книгу, хотя написана она уже давненько)
Сейчас книга по mobx ИМХО конечно, но больше похожа на официальную документацию с вкраплениями курсов (часть про создай свой фреймворк), нежели на интерактивную книгу-туториал.
Можно в рамках отдельного ISSUE обсудить струткуру =)
