### ISSUE TITLE
Сопровождать книгу примерами из codesandbox

### ISSUE THREAD

**Issue by kubk** [mobx-cookbook/mobx-cookbook.github.io#8]
От @trin4ik : "глобально я бы разработал небольшой playground для mobx+react, чтобы можно было быстро тестировать те или иные методы. отличный пример -- туториал свелта (https://svelte.dev/tutorial/basics)
мало того, что на нём можно показывать примеры работы, там же можно и давать playground. будет хорошее дополнение к книге. ну и раздел "практика" будет организовать сильно проще."

cc @zapolnoch

**Comment by kubk** [comment]
Хорошо, когда наглядно. Как у Svelte вряд ли получится сделать, но думаю можно компромиссное решение - вставлять ifram'ы с сайта codesandbox / codepen. Подобное решение я видел на medium и habr: https://habr.com/ru/post/440874/

**Comment by akaguny** [comment]
если хочется playground, то возможно стоит посмотреть в сторону https://webcontainers.io/ , разработка stackbitz.
svelte их использует https://webcontainers.io/guides/community-inspirations
также можно посмотреть на готовую имплементацию в документации react-flow (кстати тоже докадинозавр)
рендер страницы документации: https://reactflow.dev/docs/getting-started/building-a-flow/
исходник страницы документации: https://github.com/wbkd/react-flow-docs/blob/main/docs/getting-started/building-a-flow.md?plain=1#L22
компонент - рендер примера кода: https://github.com/wbkd/react-flow-docs/blob/main/src/components/CodeViewer/index.js#L9

**Comment by kubk** [comment]
@akaguny Отличная идея! Рассмотрим такой вариант. Для практики должно быть максимально наглядно

**Comment by kubk** [comment]
https://github.com/mobx-cookbook/mobx-cookbook.github.io/pull/26
